import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { AuthProvider } from "./contexts/AuthContext";


export const metadata: Metadata = {
  title: "AI Newsletter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
